project:
  type: website
  output-dir: docs
lang: es
website:
  title: "TUTO"
  favicon: "images/favicon.ico"
  navbar:
    background: primary
    search: true
    logo: "images/logo.png"
    right:
      - text: "Inicio"
        file: index.qmd
      - text: "Blog"
        file: blog.qmd
      - text: "Tuto <img src='/images/tuto_corto.png' style='vertical-align:middle; margin-right:5px;' width='20' height='20'>"
        file: "#"
      - text: "Tuto Entero <img src='/images/tuto_entero.png' style='vertical-align:middle; margin-right:5px;' width='20' height='20'>"
        menu:
          - text: "Docker"
            file: tuto_entero/docker/index.qmd
          - text: "AI Companion"
            file: tuto_entero/AI-Companion/index.qmd
          - text: "Hack Yourself: El Prompt Eres Tú"
            file: tuto_entero/01_tallerdebolsillo/index.qmd


  page-footer:
    center: 
      - text: "© 2025 TUTO 🍗 BY BARBARITA LARA"
      - href: "https://github.com/barbaritalaram"
        icon: github
      - href: "https://www.instagram.com/barbaritalaram/"
        icon: instagram
      - href: "https://barbaritalara.com/"
        icon: globe
format:
  html:
    theme: sketchy
    fontsize: 1.2em
    linestretch: 1.7

      # dark: [darkly, custom-dark.scss]
    css: custom-light.scss
    toc: true
    code-link: true
    code-tools: false
    code-fold: true
    code-summary: "Mostrar código"
    highlight-style: github